// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using CesiZen.Repository.CesiZen.Model;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Repository.Context;

public partial class CesiZenContext : DbContext
{
    public CesiZenContext(DbContextOptions<CesiZenContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Emotion> Emotions { get; set; }

    public virtual DbSet<FavoriteArticle> FavoriteArticles { get; set; }

    public virtual DbSet<InfoArticle> InfoArticles { get; set; }

    public virtual DbSet<IntensityLevel> IntensityLevels { get; set; }

    public virtual DbSet<JournalEntry> JournalEntries { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Emotion>(entity =>
        {
            entity.Property(e => e.Level).HasDefaultValue(1);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Emotions)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Emotion_User");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent).HasConstraintName("FK_Emotion_Parent");
        });

        modelBuilder.Entity<FavoriteArticle>(entity =>
        {
            entity.HasOne(d => d.Article).WithMany(p => p.FavoriteArticles).HasConstraintName("FK_FavoriteArticle_Article");

            entity.HasOne(d => d.User).WithMany(p => p.FavoriteArticles).HasConstraintName("FK_FavoriteArticle_User");
        });

        modelBuilder.Entity<InfoArticle>(entity =>
        {
            entity.Property(e => e.PublishedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Author).WithMany(p => p.InfoArticles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InfoArticle_Author");
        });

        modelBuilder.Entity<JournalEntry>(entity =>
        {
            entity.Property(e => e.LoggedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Emotion).WithMany(p => p.JournalEntries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JournalEntry_Emotion");

            entity.HasOne(d => d.IntensityLevel).WithMany(p => p.JournalEntries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JournalEntry_Intensity");

            entity.HasOne(d => d.User).WithMany(p => p.JournalEntries).HasConstraintName("FK_JournalEntry_User");
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions).HasConstraintName("FK_RolePermission_Permission");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions).HasConstraintName("FK_RolePermission_Role");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_Role");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions).HasConstraintName("FK_UserSession_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}