// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data.CesiZen.Model;

[Table("Emotion")]
public partial class Emotion
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Label { get; set; }

    [StringLength(7)]
    [Unicode(false)]
    public string Color { get; set; }

    public int? ParentId { get; set; }

    public int? CreatedByUserId { get; set; }

    [ForeignKey("CreatedByUserId")]
    [InverseProperty("Emotions")]
    public virtual User CreatedByUser { get; set; }

    [InverseProperty("Parent")]
    public virtual ICollection<Emotion> InverseParent { get; set; } = new List<Emotion>();

    [InverseProperty("Emotion")]
    public virtual ICollection<JournalEntry> JournalEntries { get; set; } = new List<JournalEntry>();

    [ForeignKey("ParentId")]
    [InverseProperty("InverseParent")]
    public virtual Emotion Parent { get; set; }
}