// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data.CesiZen.Model;

[PrimaryKey("UserId", "ArticleId")]
[Table("FavoriteArticle")]
public partial class FavoriteArticle
{
    [Key]
    public int UserId { get; set; }

    [Key]
    public int ArticleId { get; set; }

    [ForeignKey("ArticleId")]
    [InverseProperty("FavoriteArticles")]
    public virtual InfoArticle Article { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("FavoriteArticles")]
    public virtual User User { get; set; }
}