// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data.CesiZen.Model;

[Table("GlobalSetting")]
[Index("Key", Name = "UQ__GlobalSe__C41E0289E1745899", IsUnique = true)]
public partial class GlobalSetting
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Key { get; set; }

    [Required]
    public string Value { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public DateTime LastUpdated { get; set; }
}