// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data.CesiZen.Model;

[Table("InfoArticle")]
public partial class InfoArticle
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string Body { get; set; }

    public DateTime PublishedAt { get; set; }

    public int AuthorId { get; set; }

    public int? ReadTime { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string ImageUrl { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("InfoArticles")]
    public virtual User Author { get; set; }

    [InverseProperty("Article")]
    public virtual ICollection<FavoriteArticle> FavoriteArticles { get; set; } = new List<FavoriteArticle>();
}