// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data.CesiZen.Model;

[Table("Permission")]
[Index("Code", Name = "UQ_Permission_Code", IsUnique = true)]
public partial class Permission
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Label { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Code { get; set; }

    [InverseProperty("Permission")]
    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}