// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data.CesiZen.Model;

[Table("UserPrivacySetting")]
[Index("UserId", Name = "IX_UserPrivacySetting_UserId")]
public partial class UserPrivacySetting
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    public bool IsProfilePublic { get; set; }

    public bool DataSharingConsent { get; set; }

    public DateTime LastUpdated { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserPrivacySettings")]
    public virtual User User { get; set; }
}