// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data.CesiZen.Model;

[Table("UserNotificationSetting")]
[Index("UserId", Name = "IX_UserNotificationSetting_UserId")]
public partial class UserNotificationSetting
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    public bool EmailEnabled { get; set; }

    public bool PushEnabled { get; set; }

    public bool WeeklySummary { get; set; }

    public DateTime LastUpdated { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserNotificationSettings")]
    public virtual User User { get; set; }
}