// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data.CesiZen.Model;

[Table("UserPreference")]
public partial class UserPreference
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    public bool EmailNotifications { get; set; }

    public bool PushNotifications { get; set; }

    public bool DarkTheme { get; set; }

    public bool IsProfilePublic { get; set; }

    [Required]
    [StringLength(10)]
    public string Language { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserPreferences")]
    public virtual User User { get; set; }
}