// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CesiZen.Data.CesiZen.Model;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Data;

public partial class CesiZenContext : DbContext
{
    public CesiZenContext(DbContextOptions<CesiZenContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Emotion> Emotions { get; set; }

    public virtual DbSet<FavoriteArticle> FavoriteArticles { get; set; }

    public virtual DbSet<GlobalSetting> GlobalSettings { get; set; }

    public virtual DbSet<InfoArticle> InfoArticles { get; set; }

    public virtual DbSet<JournalEntry> JournalEntries { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserNotificationSetting> UserNotificationSettings { get; set; }

    public virtual DbSet<UserPreference> UserPreferences { get; set; }

    public virtual DbSet<UserPrivacySetting> UserPrivacySettings { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Emotion>(entity =>
        {
            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Emotions)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Emotion_User");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent).HasConstraintName("FK_Emotion_Parent");
        });

        modelBuilder.Entity<FavoriteArticle>(entity =>
        {
            entity.HasOne(d => d.Article).WithMany(p => p.FavoriteArticles).HasConstraintName("FK_FavoriteArticle_Article");

            entity.HasOne(d => d.User).WithMany(p => p.FavoriteArticles).HasConstraintName("FK_FavoriteArticle_User");
        });

        modelBuilder.Entity<GlobalSetting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__GlobalSe__3214EC07F745D0AB");

            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<InfoArticle>(entity =>
        {
            entity.Property(e => e.PublishedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Author).WithMany(p => p.InfoArticles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InfoArticle_Author");
        });

        modelBuilder.Entity<JournalEntry>(entity =>
        {
            entity.Property(e => e.LoggedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Emotion).WithMany(p => p.JournalEntries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JournalEntry_Emotion");

            entity.HasOne(d => d.User).WithMany(p => p.JournalEntries).HasConstraintName("FK_JournalEntry_User");
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions).HasConstraintName("FK_RolePermission_Permission");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions).HasConstraintName("FK_RolePermission_Role");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.Users).HasConstraintName("FK_User_Role");
        });

        modelBuilder.Entity<UserNotificationSetting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserNoti__3214EC0735681ED3");

            entity.Property(e => e.EmailEnabled).HasDefaultValue(true);
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PushEnabled).HasDefaultValue(true);
            entity.Property(e => e.WeeklySummary).HasDefaultValue(true);

            entity.HasOne(d => d.User).WithMany(p => p.UserNotificationSettings).HasConstraintName("FK_UserNotificationSetting_User");
        });

        modelBuilder.Entity<UserPreference>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserPref__3214EC0799CD4D38");

            entity.Property(e => e.EmailNotifications).HasDefaultValue(true);
            entity.Property(e => e.Language).HasDefaultValue("FR");
            entity.Property(e => e.PushNotifications).HasDefaultValue(true);

            entity.HasOne(d => d.User).WithMany(p => p.UserPreferences).HasConstraintName("FK_UserPreference_User");
        });

        modelBuilder.Entity<UserPrivacySetting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserPriv__3214EC07A5727B25");

            entity.Property(e => e.DataSharingConsent).HasDefaultValue(true);
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.User).WithMany(p => p.UserPrivacySettings).HasConstraintName("FK_UserPrivacySetting_User");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions).HasConstraintName("FK_UserSession_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}