// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Repository.CesiZen.Model;

[Table("IntensityLevel")]
public partial class IntensityLevel
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Label { get; set; } = null!;

    public int Value { get; set; }

    [InverseProperty("IntensityLevel")]
    public virtual ICollection<JournalEntry> JournalEntries { get; set; } = new List<JournalEntry>();
}