// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Repository.CesiZen.Model;

[Table("JournalEntry")]
public partial class JournalEntry
{
    [Key]
    public int Id { get; set; }

    public DateTime LoggedAt { get; set; }

    [Column(TypeName = "text")]
    public string? Content { get; set; }

    public int UserId { get; set; }

    public int EmotionId { get; set; }

    public int IntensityLevelId { get; set; }

    [ForeignKey("EmotionId")]
    [InverseProperty("JournalEntries")]
    public virtual Emotion Emotion { get; set; } = null!;

    [ForeignKey("IntensityLevelId")]
    [InverseProperty("JournalEntries")]
    public virtual IntensityLevel IntensityLevel { get; set; } = null!;

    [ForeignKey("UserId")]
    [InverseProperty("JournalEntries")]
    public virtual User User { get; set; } = null!;
}