// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CesiZen.Repository.CesiZen.Model;

[Table("User")]
[Index("Email", Name = "UQ_User_Email", IsUnique = true)]
[Index("Username", Name = "UQ_User_Username", IsUnique = true)]
public partial class User
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; } = null!;

    [Unicode(false)]
    public string PasswordHash { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string? DisplayName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int RoleId { get; set; }

    [InverseProperty("CreatedByUser")]
    public virtual ICollection<Emotion> Emotions { get; set; } = new List<Emotion>();

    [InverseProperty("User")]
    public virtual ICollection<FavoriteArticle> FavoriteArticles { get; set; } = new List<FavoriteArticle>();

    [InverseProperty("Author")]
    public virtual ICollection<InfoArticle> InfoArticles { get; set; } = new List<InfoArticle>();

    [InverseProperty("User")]
    public virtual ICollection<JournalEntry> JournalEntries { get; set; } = new List<JournalEntry>();

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; } = null!;

    [InverseProperty("User")]
    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();
}